name: Verify code integrity
on: push
jobs:
  verify-integrity:
    name: Verify code integrity
    runs-on: ubuntu-latest
    steps:
      # Checkout code and setup NodeJS
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: '16'
      # Run tasks to verify code.
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test
